title: <img src="https://raw.githubusercontent.com/yumm-b612/moji.py/main/utils/assets/moji/moji_hd.png"/> yumyum#6512
description: Hullo, am yum. I like cashews and pistachios and am severely allergic to seafood's.

theme: jekyll-theme-cayman
