title: <img height="20%" width="20%" src="https://avatars.githubusercontent.com/u/75433579?v=4"/> definitely not yum#6512
description: Elo, am yum, one can just call me yum :D i like cashews, pistachios and am highly allergic to seafood's and hates pickles :p

theme: jekyll-theme-cayman
